id: dceb0cbc-1bcc-42b4-934c-40595d892fab
name: ProjectContext
type: c4-project
description: This is a sample project configuration for C4 model generation.
children:
  - id: f1f4b979-4624-4bcc-b485-70a76ebe4572
    type: software-system
  - id: 579f5d6b-485d-4040-9ede-b0a1734439fe
    type: person
tenantId: 5f37364f-201e-47ea-2e89-08dd02619fda
